# This was generated by `rails json_params:generate`
#
# @name ChatThreadStrongParameter
#
# @attr [integer] id
# @attr [Array<integer>] participants
# @attr [integer] newestChatId
class Params::ChaThread; end
