# This was generated by `rails json_params:generate`
#
# @name ChatStrongParameter
#
# @attr [integer] id
# @attr [integer] chatThreadId
# @attr [integer] senderId
# @attr [integer] contentType
# @attr [string] body
# @attr [hash] itemList
# @attr [string] result
# @attr [boolean] expired
class Params::Chat; end
