# This was generated by `rails json_params:generate`
#
# @name DailyLogStrongParameter
#
# @attr [integer] symptom
# @attr [integer] health
# @attr [string] healthMemo
# @attr [boolean] medicina
# @attr [string] medicinaMemo
# @attr [string] photograph
# @attr [string] photographMemo
class Params::DailyLog; end
