# This was generated by `rails json_params:generate`
#
# @name DailyLogStrongParameter
#
# @attr [integer] id
# @attr [integer] userId
# @attr [date] date
# @attr [string] symptom
# @attr [integer] health
# @attr [string] healthMemo
# @attr [boolean] medicina
# @attr [string] medicinaMemo
# @attr [Array<string>] photograph
# @attr [string] photographMemo
class Params::DailyLog; end
