# This was generated by `rails json_params:generate`
#
# @name ExperienceStrongParameter
#
# @attr [integer] id
# @attr [integer] userId
# @attr [integer] activityId
# @attr [string] activityType
# @attr [date-time] createdAt
# @attr [date-time] updatedAt
class Params::Experience; end
