# This was generated by `rails json_params:generate`
#
# @name FriendExperienceStrongParameter
#
# @attr [integer] id
# @attr [integer] userId
# @attr [integer] activityId
# @attr [string] activityType
# @attr [integer] fromUserId
# @attr [date-time] createdAt
# @attr [date-time] updatedAt
# @attr [string] name
class Params::FriendExperience; end
