# This was generated by `rails json_params:generate`
#
# @name MicropostStrongParameter
#
# @attr [integer] id
# @attr [string] content
# @attr [integer] userId
# @attr [string] picture
# @attr [date-time] createdAt
# @attr [date-time] updatedAt
class Params::Micropost; end
