# This was generated by `rails json_params:generate`
#
# @name RelationshipStrongParameter
#
# @attr [integer] id
# @attr [integer] followerId
# @attr [integer] followedId
class Params::Relationship; end
