# This was generated by `rails json_params:generate`
#
# @name UserStrongParameter
#
# @attr [integer] id
# @attr [string] email
# @attr [string] encryptedPassword
# @attr [string] resetPasswordToken
# @attr [date-time] resetPasswordSentAt
# @attr [date-time] rememberCreatedAt
# @attr [integer] signInCount
# @attr [date-time] currentSignInAt
# @attr [date-time] lastSignInAt
# @attr [string] currentSignInIp
# @attr [string] lastSignInIp
# @attr [string] confirmationToken
# @attr [date-time] confirmedAt
# @attr [date-time] confirmationSentAt
# @attr [string] unconfirmedEmail
# @attr [string] name
# @attr [boolean] admin
# @attr [string] selfIntroduction
# @attr [integer] rank
# @attr [integer] titleOfHonor
# @attr [integer] classification
# @attr [boolean] atopic
# @attr [boolean] asthma
# @attr [boolean] rhinitis
# @attr [boolean] pollen
# @attr [boolean] gastroenteritis
# @attr [boolean] conjunctivitis
# @attr [string] accessToken
class Params::User; end
