# This was generated by `rails json_params:generate`
#
# @name UserStrongParameter
#
# @attr [integer] id
# @attr [string] email
# @attr [string] encryptedPassword
# @attr [string] resetPasswordToken
# @attr [date-time] resetPasswordSentAt
# @attr [date-time] rememberCreatedAt
# @attr [integer] signInCount
# @attr [date-time] currentSignInAt
# @attr [date-time] lastSignInAt
# @attr [string] currentSignInIp
# @attr [string] lastSignInIp
# @attr [string] confirmationToken
# @attr [date-time] confirmedAt
# @attr [date-time] confirmationSentAt
# @attr [string] unconfirmedEmail
# @attr [string] name
# @attr [boolean] admin
# @attr [string] selfIntroduction
# @attr [integer] rank
# @attr [integer] titleOfHonor
# @attr [integer] classification
# @attr [boolean] atopic
# @attr [boolean] asthma
# @attr [boolean] rhinitis
# @attr [boolean] pollen
# @attr [boolean] gastroenteritis
# @attr [boolean] conjunctivitis
# @attr [boolean] allergenGroupInekakafun
# @attr [boolean] allergenGroupZassoukafun
# @attr [boolean] allergenGroupJyukikafun
# @attr [boolean] allergenGroupChiri
# @attr [boolean] allergenGroupDani
# @attr [boolean] allergenGroupShinkin
# @attr [boolean] allergenGroupSaikin
# @attr [boolean] allergenGroupDoubutsu
# @attr [boolean] allergenGroupSyokugyou
# @attr [boolean] allergenGroupTamago
# @attr [boolean] allergenGroupNyuuseihin
# @attr [boolean] allergenGroupGyorui
# @attr [boolean] allergenGroupKoukakurui
# @attr [boolean] allergenGroupIkatako
# @attr [boolean] allergenGroupKomugi
# @attr [boolean] allergenGroupKomugiigai
# @attr [boolean] allergenGroupNikurui
# @attr [boolean] allergenGroupMamerui
# @attr [boolean] allergenGroupKudamonorui
# @attr [boolean] allergenGroupYasai
# @attr [boolean] allergenGroupSonota
# @attr [boolean] allergenGroupKiseityuu
# @attr [boolean] allergenGroupYakubutsu
# @attr [boolean] allergenGroupKontyuu
# @attr [string] accessToken
class Params::User; end
