source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "2.3.3"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.2'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'rb-readline'
gem 'active_hash'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# 画像
gem 'carrierwave',             '~> 0.11'
gem 'mini_magick',             '~> 4.5'
gem 'fog',                     '~> 1.38'

# ダミーデータ作成
gem 'faker',        '~> 1.6'
gem 'as-duration'

group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # rspec
  gem 'rspec-rails', '~> 3.5'
  gem 'fuubar'
  gem 'factory_girl_rails'

end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console',           '~> 3.1'

    # リアルタイムテスト
  gem 'guard-rspec', require: false # guardでrspecを動かす
  gem 'terminal-notifier'
  gem 'terminal-notifier-guard'  # デスクトップ通知を行う

  gem 'rails-erd', require: false
end

group :test do
  gem 'guard',               '~> 2.13'
  gem 'pg', '~> 0.18'
end

group :production do
  gem 'pg', '~> 0.18'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
