# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170402113409) do

  create_table "iges", force: :cascade do |t|
    t.integer  "user_id"
    t.date     "test_date"
    t.integer  "test_category"
    t.decimal  "ige_value",                         precision: 24, scale: 20
    t.integer  "ige_unit"
    t.decimal  "allergen_harugaya_value"
    t.decimal  "allergen_gyougishiba_value"
    t.decimal  "allergen_kamogaya_value"
    t.decimal  "allergen_hirohaushinokegusa_value"
    t.decimal  "allergen_hosomugi_value"
    t.decimal  "allergen_ooawagaeri_value"
    t.decimal  "allergen_ashi_value"
    t.decimal  "allergen_nagahagusa_value"
    t.decimal  "allergen_konukagusaZoku_value"
    t.decimal  "allergen_seibanmorokoshi_value"
    t.decimal  "allergen_komugiZoku_value"
    t.decimal  "allergen_oosuzumenoteppou_value"
    t.decimal  "allergen_suzumenohieZoku_value"
    t.decimal  "allergen_butakusakongoubu1_value"
    t.decimal  "allergen_butakusa_value"
    t.decimal  "allergen_butakusamodoki_value"
    t.decimal  "allergen_oobutakusa_value"
    t.decimal  "allergen_nigayomogi_value"
    t.decimal  "allergen_yomogi_value"
    t.decimal  "allergen_huransugiku_value"
    t.decimal  "allergen_tanpopoZoku_value"
    t.decimal  "allergen_heraobako_value"
    t.decimal  "allergen_shiroza_value"
    t.decimal  "allergen_akinokirinsou_value"
    t.decimal  "allergen_himesuiba_value"
    t.decimal  "allergen_irakusaZoku_value"
    t.decimal  "allergen_kanamugura_value"
    t.decimal  "allergen_kaedeZoku_value"
    t.decimal  "allergen_hannokiZoku_value"
    t.decimal  "allergen_shirakanbaZoku_value"
    t.decimal  "allergen_bunaZoku_value"
    t.decimal  "allergen_byakushinZoku_value"
    t.decimal  "allergen_konaraZoku_value"
    t.decimal  "allergen_nireZoku_value"
    t.decimal  "allergen_olive_value"
    t.decimal  "allergen_kurumiZoku_value"
    t.decimal  "allergen_yanagiZoku_value"
    t.decimal  "allergen_matsuZoku_value"
    t.decimal  "allergen_sugi_value"
    t.decimal  "allergen_acaciaZoku_value"
    t.decimal  "allergen_hinoki_value"
    t.decimal  "allergen_kuwaZoku_value"
    t.decimal  "allergen_housedust1_value"
    t.decimal  "allergen_housedust2_value"
    t.decimal  "allergen_yakehyouhidani_value"
    t.decimal  "allergen_konahyouhidani_value"
    t.decimal  "allergen_ashibutokonadani_value"
    t.decimal  "allergen_sayaashinidani_value"
    t.decimal  "allergen_kenagakonadani_value"
    t.decimal  "allergen_penicillium_value"
    t.decimal  "allergen_cladosporium_value"
    t.decimal  "allergen_aspergillosis_value"
    t.decimal  "allergen_mucor_value"
    t.decimal  "allergen_candida_value"
    t.decimal  "allergen_alternaria_value"
    t.decimal  "allergen_helminthosporium_value"
    t.decimal  "allergen_pityrosporium_value"
    t.decimal  "allergen_trichophyton_value"
    t.decimal  "allergen_malassezia_value"
    t.decimal  "allergen_kiirobudoukyukinA_value"
    t.decimal  "allergen_kiirobudoukyukinB_value"
    t.decimal  "allergen_nekoHisetsu_value"
    t.decimal  "allergen_umaHisetsu_value"
    t.decimal  "allergen_ushiHisetsu_value"
    t.decimal  "allergen_inuHisetsu_value"
    t.decimal  "allergen_marmotJyouhi_value"
    t.decimal  "allergen_hatoFun_value"
    t.decimal  "allergen_gatyouUmou_value"
    t.decimal  "allergen_sekiseiinkoFun_value"
    t.decimal  "allergen_sekiseiinkoUmou_value"
    t.decimal  "allergen_yagiJyouhi_value"
    t.decimal  "allergen_hitsujiJyouhi_value"
    t.decimal  "allergen_katoJyouhi_value"
    t.decimal  "allergen_butaJyouhi_value"
    t.decimal  "allergen_hamsterJyouhi_value"
    t.decimal  "allergen_niwatoriUmou_value"
    t.decimal  "allergen_ahiruUmou_value"
    t.decimal  "allergen_ratt_value"
    t.decimal  "allergen_mouse_value"
    t.decimal  "allergen_oobakosyushi_value"
    t.decimal  "allergen_kinu_value"
    t.decimal  "allergen_isocyanateTDI_value"
    t.decimal  "allergen_isocyanateMDI_value"
    t.decimal  "allergen_isocyanateHDI_value"
    t.decimal  "allergen_ethyleneoxide_value"
    t.decimal  "allergen_musuihutalsan_value"
    t.decimal  "allergen_formalin_value"
    t.decimal  "allergen_latex_value"
    t.decimal  "allergen_men_value"
    t.decimal  "allergen_ranpaku_value"
    t.decimal  "allergen_ranou_value"
    t.decimal  "allergen_ovomucoid_value"
    t.decimal  "allergen_milk_value"
    t.decimal  "allergen_alpha_actalbumin_value"
    t.decimal  "allergen_beta_lactoglobulin_value"
    t.decimal  "allergen_casein_value"
    t.decimal  "allergen_cheese_value"
    t.decimal  "allergen_moldcheese_value"
    t.decimal  "allergen_tara_value"
    t.decimal  "allergen_maguro_value"
    t.decimal  "allergen_sake_value"
    t.decimal  "allergen_saba_value"
    t.decimal  "allergen_aji_value"
    t.decimal  "allergen_iwashi_value"
    t.decimal  "allergen_karei_value"
    t.decimal  "allergen_ikura_value"
    t.decimal  "allergen_tarako_value"
    t.decimal  "allergen_kani_value"
    t.decimal  "allergen_ebi_value"
    t.decimal  "allergen_murasakigai_value"
    t.decimal  "allergen_lobster_value"
    t.decimal  "allergen_asari_value"
    t.decimal  "allergen_kaki_value"
    t.decimal  "allergen_hotate_value"
    t.decimal  "allergen_ika_value"
    t.decimal  "allergen_tako_value"
    t.decimal  "allergen_komugi_value"
    t.decimal  "allergen_gluten_value"
    t.decimal  "allergen_oh_5gliadin_value"
    t.decimal  "allergen_raimugi_value"
    t.decimal  "allergen_oomugi_value"
    t.decimal  "allergen_ootomugi_value"
    t.decimal  "allergen_toumorokoshi_value"
    t.decimal  "allergen_kome_value"
    t.decimal  "allergen_soba_value"
    t.decimal  "allergen_beerkoubo_value"
    t.decimal  "allergen_kibi_value"
    t.decimal  "allergen_awa_value"
    t.decimal  "allergen_hie_value"
    t.decimal  "allergen_bakuga_value"
    t.decimal  "allergen_butaniku_value"
    t.decimal  "allergen_gyuniku_value"
    t.decimal  "allergen_toriniku_value"
    t.decimal  "allergen_youniku_value"
    t.decimal  "allergen_endou_value"
    t.decimal  "allergen_peanuts_value"
    t.decimal  "allergen_daizu_value"
    t.decimal  "allergen_ingen_value"
    t.decimal  "allergen_hashibami_value"
    t.decimal  "allergen_brazilnuts_value"
    t.decimal  "allergen_almond_value"
    t.decimal  "allergen_coconut_value"
    t.decimal  "allergen_cacao_value"
    t.decimal  "allergen_cashewnuts_value"
    t.decimal  "allergen_kurumi_value"
    t.decimal  "allergen_arah2_value"
    t.decimal  "allergen_orange_value"
    t.decimal  "allergen_ichigo_value"
    t.decimal  "allergen_ringo_value"
    t.decimal  "allergen_kiwi_value"
    t.decimal  "allergen_melon_value"
    t.decimal  "allergen_mango_value"
    t.decimal  "allergen_banana_value"
    t.decimal  "allergen_younashi_value"
    t.decimal  "allergen_momo_value"
    t.decimal  "allergen_avocado_value"
    t.decimal  "allergen_grapefruit_value"
    t.decimal  "allergen_suika_value"
    t.decimal  "allergen_tomato_value"
    t.decimal  "allergen_ninjin_value"
    t.decimal  "allergen_jyagaimo_value"
    t.decimal  "allergen_ninniku_value"
    t.decimal  "allergen_tamanegi_value"
    t.decimal  "allergen_takenoko_value"
    t.decimal  "allergen_satsumaimo_value"
    t.decimal  "allergen_celery_value"
    t.decimal  "allergen_parsley_value"
    t.decimal  "allergen_yamaimo_value"
    t.decimal  "allergen_hourensou_value"
    t.decimal  "allergen_kabocha_value"
    t.decimal  "allergen_hitoinsulin_food_value"
    t.decimal  "allergen_gelatin_value"
    t.decimal  "allergen_goma_value"
    t.decimal  "allergen_mustard_value"
    t.decimal  "allergen_kaichu_value"
    t.decimal  "allergen_anisakis_value"
    t.decimal  "allergen_hitoinsulin_etc_value"
    t.decimal  "allergen_mitsubachi_value"
    t.decimal  "allergen_suzumebachi_value"
    t.decimal  "allergen_ashinagabachi_value"
    t.decimal  "allergen_gokiburi_value"
    t.decimal  "allergen_yusurika_value"
    t.decimal  "allergen_ga_value"
    t.decimal  "allergen_yabuka_value"
    t.decimal  "allergen_doubutsuJyouhi_value"
    t.decimal  "allergen_syokumotsu_value"
    t.decimal  "allergen_kokumotsu_value"
    t.decimal  "allergen_ineka_value"
    t.decimal  "allergen_kabi_value"
    t.decimal  "allergen_zassou_value"
    t.integer  "allergen_harugaya_unit"
    t.integer  "allergen_gyougishiba_unit"
    t.integer  "allergen_kamogaya_unit"
    t.integer  "allergen_hirohaushinokegusa_unit"
    t.integer  "allergen_hosomugi_unit"
    t.integer  "allergen_ooawagaeri_unit"
    t.integer  "allergen_ashi_unit"
    t.integer  "allergen_nagahagusa_unit"
    t.integer  "allergen_konukagusaZoku_unit"
    t.integer  "allergen_seibanmorokoshi_unit"
    t.integer  "allergen_komugiZoku_unit"
    t.integer  "allergen_oosuzumenoteppou_unit"
    t.integer  "allergen_suzumenohieZoku_unit"
    t.integer  "allergen_butakusakongoubu1_unit"
    t.integer  "allergen_butakusa_unit"
    t.integer  "allergen_butakusamodoki_unit"
    t.integer  "allergen_oobutakusa_unit"
    t.integer  "allergen_nigayomogi_unit"
    t.integer  "allergen_yomogi_unit"
    t.integer  "allergen_huransugiku_unit"
    t.integer  "allergen_tanpopoZoku_unit"
    t.integer  "allergen_heraobako_unit"
    t.integer  "allergen_shiroza_unit"
    t.integer  "allergen_akinokirinsou_unit"
    t.integer  "allergen_himesuiba_unit"
    t.integer  "allergen_irakusaZoku_unit"
    t.integer  "allergen_kanamugura_unit"
    t.integer  "allergen_kaedeZoku_unit"
    t.integer  "allergen_hannokiZoku_unit"
    t.integer  "allergen_shirakanbaZoku_unit"
    t.integer  "allergen_bunaZoku_unit"
    t.integer  "allergen_byakushinZoku_unit"
    t.integer  "allergen_konaraZoku_unit"
    t.integer  "allergen_nireZoku_unit"
    t.integer  "allergen_olive_unit"
    t.integer  "allergen_kurumiZoku_unit"
    t.integer  "allergen_yanagiZoku_unit"
    t.integer  "allergen_matsuZoku_unit"
    t.integer  "allergen_sugi_unit"
    t.integer  "allergen_acaciaZoku_unit"
    t.integer  "allergen_hinoki_unit"
    t.integer  "allergen_kuwaZoku_unit"
    t.integer  "allergen_housedust1_unit"
    t.integer  "allergen_housedust2_unit"
    t.integer  "allergen_yakehyouhidani_unit"
    t.integer  "allergen_konahyouhidani_unit"
    t.integer  "allergen_ashibutokonadani_unit"
    t.integer  "allergen_sayaashinidani_unit"
    t.integer  "allergen_kenagakonadani_unit"
    t.integer  "allergen_penicillium_unit"
    t.integer  "allergen_cladosporium_unit"
    t.integer  "allergen_aspergillosis_unit"
    t.integer  "allergen_mucor_unit"
    t.integer  "allergen_candida_unit"
    t.integer  "allergen_alternaria_unit"
    t.integer  "allergen_helminthosporium_unit"
    t.integer  "allergen_pityrosporium_unit"
    t.integer  "allergen_trichophyton_unit"
    t.integer  "allergen_malassezia_unit"
    t.integer  "allergen_kiirobudoukyukinA_unit"
    t.integer  "allergen_kiirobudoukyukinB_unit"
    t.integer  "allergen_nekoHisetsu_unit"
    t.integer  "allergen_umaHisetsu_unit"
    t.integer  "allergen_ushiHisetsu_unit"
    t.integer  "allergen_inuHisetsu_unit"
    t.integer  "allergen_marmotJyouhi_unit"
    t.integer  "allergen_hatoFun_unit"
    t.integer  "allergen_gatyouUmou_unit"
    t.integer  "allergen_sekiseiinkoFun_unit"
    t.integer  "allergen_sekiseiinkoUmou_unit"
    t.integer  "allergen_yagiJyouhi_unit"
    t.integer  "allergen_hitsujiJyouhi_unit"
    t.integer  "allergen_katoJyouhi_unit"
    t.integer  "allergen_butaJyouhi_unit"
    t.integer  "allergen_hamsterJyouhi_unit"
    t.integer  "allergen_niwatoriUmou_unit"
    t.integer  "allergen_ahiruUmou_unit"
    t.integer  "allergen_ratt_unit"
    t.integer  "allergen_mouse_unit"
    t.integer  "allergen_oobakosyushi_unit"
    t.integer  "allergen_kinu_unit"
    t.integer  "allergen_isocyanateTDI_unit"
    t.integer  "allergen_isocyanateMDI_unit"
    t.integer  "allergen_isocyanateHDI_unit"
    t.integer  "allergen_ethyleneoxide_unit"
    t.integer  "allergen_musuihutalsan_unit"
    t.integer  "allergen_formalin_unit"
    t.integer  "allergen_latex_unit"
    t.integer  "allergen_men_unit"
    t.integer  "allergen_ranpaku_unit"
    t.integer  "allergen_ranou_unit"
    t.integer  "allergen_ovomucoid_unit"
    t.integer  "allergen_milk_unit"
    t.integer  "allergen_alpha_actalbumin_unit"
    t.integer  "allergen_beta_lactoglobulin_unit"
    t.integer  "allergen_casein_unit"
    t.integer  "allergen_cheese_unit"
    t.integer  "allergen_moldcheese_unit"
    t.integer  "allergen_tara_unit"
    t.integer  "allergen_maguro_unit"
    t.integer  "allergen_sake_unit"
    t.integer  "allergen_saba_unit"
    t.integer  "allergen_aji_unit"
    t.integer  "allergen_iwashi_unit"
    t.integer  "allergen_karei_unit"
    t.integer  "allergen_ikura_unit"
    t.integer  "allergen_tarako_unit"
    t.integer  "allergen_kani_unit"
    t.integer  "allergen_ebi_unit"
    t.integer  "allergen_murasakigai_unit"
    t.integer  "allergen_lobster_unit"
    t.integer  "allergen_asari_unit"
    t.integer  "allergen_kaki_unit"
    t.integer  "allergen_hotate_unit"
    t.integer  "allergen_ika_unit"
    t.integer  "allergen_tako_unit"
    t.integer  "allergen_komugi_unit"
    t.integer  "allergen_gluten_unit"
    t.integer  "allergen_oh_5gliadin_unit"
    t.integer  "allergen_raimugi_unit"
    t.integer  "allergen_oomugi_unit"
    t.integer  "allergen_ootomugi_unit"
    t.integer  "allergen_toumorokoshi_unit"
    t.integer  "allergen_kome_unit"
    t.integer  "allergen_soba_unit"
    t.integer  "allergen_beerkoubo_unit"
    t.integer  "allergen_kibi_unit"
    t.integer  "allergen_awa_unit"
    t.integer  "allergen_hie_unit"
    t.integer  "allergen_bakuga_unit"
    t.integer  "allergen_butaniku_unit"
    t.integer  "allergen_gyuniku_unit"
    t.integer  "allergen_toriniku_unit"
    t.integer  "allergen_youniku_unit"
    t.integer  "allergen_endou_unit"
    t.integer  "allergen_peanuts_unit"
    t.integer  "allergen_daizu_unit"
    t.integer  "allergen_ingen_unit"
    t.integer  "allergen_hashibami_unit"
    t.integer  "allergen_brazilnuts_unit"
    t.integer  "allergen_almond_unit"
    t.integer  "allergen_coconut_unit"
    t.integer  "allergen_cacao_unit"
    t.integer  "allergen_cashewnuts_unit"
    t.integer  "allergen_kurumi_unit"
    t.integer  "allergen_arah2_unit"
    t.integer  "allergen_orange_unit"
    t.integer  "allergen_ichigo_unit"
    t.integer  "allergen_ringo_unit"
    t.integer  "allergen_kiwi_unit"
    t.integer  "allergen_melon_unit"
    t.integer  "allergen_mango_unit"
    t.integer  "allergen_banana_unit"
    t.integer  "allergen_younashi_unit"
    t.integer  "allergen_momo_unit"
    t.integer  "allergen_avocado_unit"
    t.integer  "allergen_grapefruit_unit"
    t.integer  "allergen_suika_unit"
    t.integer  "allergen_tomato_unit"
    t.integer  "allergen_ninjin_unit"
    t.integer  "allergen_jyagaimo_unit"
    t.integer  "allergen_ninniku_unit"
    t.integer  "allergen_tamanegi_unit"
    t.integer  "allergen_takenoko_unit"
    t.integer  "allergen_satsumaimo_unit"
    t.integer  "allergen_celery_unit"
    t.integer  "allergen_parsley_unit"
    t.integer  "allergen_yamaimo_unit"
    t.integer  "allergen_hourensou_unit"
    t.integer  "allergen_kabocha_unit"
    t.integer  "allergen_hitoinsulin_food_unit"
    t.integer  "allergen_gelatin_unit"
    t.integer  "allergen_goma_unit"
    t.integer  "allergen_mustard_unit"
    t.integer  "allergen_kaichu_unit"
    t.integer  "allergen_anisakis_unit"
    t.integer  "allergen_hitoinsulin_etc_unit"
    t.integer  "allergen_mitsubachi_unit"
    t.integer  "allergen_suzumebachi_unit"
    t.integer  "allergen_ashinagabachi_unit"
    t.integer  "allergen_gokiburi_unit"
    t.integer  "allergen_yusurika_unit"
    t.integer  "allergen_ga_unit"
    t.integer  "allergen_yabuka_unit"
    t.integer  "allergen_doubutsuJyouhi_unit"
    t.integer  "allergen_syokumotsu_unit"
    t.integer  "allergen_kokumotsu_unit"
    t.integer  "allergen_ineka_unit"
    t.integer  "allergen_kabi_unit"
    t.integer  "allergen_zassou_unit"
    t.integer  "allergen_harugaya_class"
    t.integer  "allergen_gyougishiba_class"
    t.integer  "allergen_kamogaya_class"
    t.integer  "allergen_hirohaushinokegusa_class"
    t.integer  "allergen_hosomugi_class"
    t.integer  "allergen_ooawagaeri_class"
    t.integer  "allergen_ashi_class"
    t.integer  "allergen_nagahagusa_class"
    t.integer  "allergen_konukagusaZoku_class"
    t.integer  "allergen_seibanmorokoshi_class"
    t.integer  "allergen_komugiZoku_class"
    t.integer  "allergen_oosuzumenoteppou_class"
    t.integer  "allergen_suzumenohieZoku_class"
    t.integer  "allergen_butakusakongoubu1_class"
    t.integer  "allergen_butakusa_class"
    t.integer  "allergen_butakusamodoki_class"
    t.integer  "allergen_oobutakusa_class"
    t.integer  "allergen_nigayomogi_class"
    t.integer  "allergen_yomogi_class"
    t.integer  "allergen_huransugiku_class"
    t.integer  "allergen_tanpopoZoku_class"
    t.integer  "allergen_heraobako_class"
    t.integer  "allergen_shiroza_class"
    t.integer  "allergen_akinokirinsou_class"
    t.integer  "allergen_himesuiba_class"
    t.integer  "allergen_irakusaZoku_class"
    t.integer  "allergen_kanamugura_class"
    t.integer  "allergen_kaedeZoku_class"
    t.integer  "allergen_hannokiZoku_class"
    t.integer  "allergen_shirakanbaZoku_class"
    t.integer  "allergen_bunaZoku_class"
    t.integer  "allergen_byakushinZoku_class"
    t.integer  "allergen_konaraZoku_class"
    t.integer  "allergen_nireZoku_class"
    t.integer  "allergen_olive_class"
    t.integer  "allergen_kurumiZoku_class"
    t.integer  "allergen_yanagiZoku_class"
    t.integer  "allergen_matsuZoku_class"
    t.integer  "allergen_sugi_class"
    t.integer  "allergen_acaciaZoku_class"
    t.integer  "allergen_hinoki_class"
    t.integer  "allergen_kuwaZoku_class"
    t.integer  "allergen_housedust1_class"
    t.integer  "allergen_housedust2_class"
    t.integer  "allergen_yakehyouhidani_class"
    t.integer  "allergen_konahyouhidani_class"
    t.integer  "allergen_ashibutokonadani_class"
    t.integer  "allergen_sayaashinidani_class"
    t.integer  "allergen_kenagakonadani_class"
    t.integer  "allergen_penicillium_class"
    t.integer  "allergen_cladosporium_class"
    t.integer  "allergen_aspergillosis_class"
    t.integer  "allergen_mucor_class"
    t.integer  "allergen_candida_class"
    t.integer  "allergen_alternaria_class"
    t.integer  "allergen_helminthosporium_class"
    t.integer  "allergen_pityrosporium_class"
    t.integer  "allergen_trichophyton_class"
    t.integer  "allergen_malassezia_class"
    t.integer  "allergen_kiirobudoukyukinA_class"
    t.integer  "allergen_kiirobudoukyukinB_class"
    t.integer  "allergen_nekoHisetsu_class"
    t.integer  "allergen_umaHisetsu_class"
    t.integer  "allergen_ushiHisetsu_class"
    t.integer  "allergen_inuHisetsu_class"
    t.integer  "allergen_marmotJyouhi_class"
    t.integer  "allergen_hatoFun_class"
    t.integer  "allergen_gatyouUmou_class"
    t.integer  "allergen_sekiseiinkoFun_class"
    t.integer  "allergen_sekiseiinkoUmou_class"
    t.integer  "allergen_yagiJyouhi_class"
    t.integer  "allergen_hitsujiJyouhi_class"
    t.integer  "allergen_katoJyouhi_class"
    t.integer  "allergen_butaJyouhi_class"
    t.integer  "allergen_hamsterJyouhi_class"
    t.integer  "allergen_niwatoriUmou_class"
    t.integer  "allergen_ahiruUmou_class"
    t.integer  "allergen_ratt_class"
    t.integer  "allergen_mouse_class"
    t.integer  "allergen_oobakosyushi_class"
    t.integer  "allergen_kinu_class"
    t.integer  "allergen_isocyanateTDI_class"
    t.integer  "allergen_isocyanateMDI_class"
    t.integer  "allergen_isocyanateHDI_class"
    t.integer  "allergen_ethyleneoxide_class"
    t.integer  "allergen_musuihutalsan_class"
    t.integer  "allergen_formalin_class"
    t.integer  "allergen_latex_class"
    t.integer  "allergen_men_class"
    t.integer  "allergen_ranpaku_class"
    t.integer  "allergen_ranou_class"
    t.integer  "allergen_ovomucoid_class"
    t.integer  "allergen_milk_class"
    t.integer  "allergen_alpha_actalbumin_class"
    t.integer  "allergen_beta_lactoglobulin_class"
    t.integer  "allergen_casein_class"
    t.integer  "allergen_cheese_class"
    t.integer  "allergen_moldcheese_class"
    t.integer  "allergen_tara_class"
    t.integer  "allergen_maguro_class"
    t.integer  "allergen_sake_class"
    t.integer  "allergen_saba_class"
    t.integer  "allergen_aji_class"
    t.integer  "allergen_iwashi_class"
    t.integer  "allergen_karei_class"
    t.integer  "allergen_ikura_class"
    t.integer  "allergen_tarako_class"
    t.integer  "allergen_kani_class"
    t.integer  "allergen_ebi_class"
    t.integer  "allergen_murasakigai_class"
    t.integer  "allergen_lobster_class"
    t.integer  "allergen_asari_class"
    t.integer  "allergen_kaki_class"
    t.integer  "allergen_hotate_class"
    t.integer  "allergen_ika_class"
    t.integer  "allergen_tako_class"
    t.integer  "allergen_komugi_class"
    t.integer  "allergen_gluten_class"
    t.integer  "allergen_oh_5gliadin_class"
    t.integer  "allergen_raimugi_class"
    t.integer  "allergen_oomugi_class"
    t.integer  "allergen_ootomugi_class"
    t.integer  "allergen_toumorokoshi_class"
    t.integer  "allergen_kome_class"
    t.integer  "allergen_soba_class"
    t.integer  "allergen_beerkoubo_class"
    t.integer  "allergen_kibi_class"
    t.integer  "allergen_awa_class"
    t.integer  "allergen_hie_class"
    t.integer  "allergen_bakuga_class"
    t.integer  "allergen_butaniku_class"
    t.integer  "allergen_gyuniku_class"
    t.integer  "allergen_toriniku_class"
    t.integer  "allergen_youniku_class"
    t.integer  "allergen_endou_class"
    t.integer  "allergen_peanuts_class"
    t.integer  "allergen_daizu_class"
    t.integer  "allergen_ingen_class"
    t.integer  "allergen_hashibami_class"
    t.integer  "allergen_brazilnuts_class"
    t.integer  "allergen_almond_class"
    t.integer  "allergen_coconut_class"
    t.integer  "allergen_cacao_class"
    t.integer  "allergen_cashewnuts_class"
    t.integer  "allergen_kurumi_class"
    t.integer  "allergen_arah2_class"
    t.integer  "allergen_orange_class"
    t.integer  "allergen_ichigo_class"
    t.integer  "allergen_ringo_class"
    t.integer  "allergen_kiwi_class"
    t.integer  "allergen_melon_class"
    t.integer  "allergen_mango_class"
    t.integer  "allergen_banana_class"
    t.integer  "allergen_younashi_class"
    t.integer  "allergen_momo_class"
    t.integer  "allergen_avocado_class"
    t.integer  "allergen_grapefruit_class"
    t.integer  "allergen_suika_class"
    t.integer  "allergen_tomato_class"
    t.integer  "allergen_ninjin_class"
    t.integer  "allergen_jyagaimo_class"
    t.integer  "allergen_ninniku_class"
    t.integer  "allergen_tamanegi_class"
    t.integer  "allergen_takenoko_class"
    t.integer  "allergen_satsumaimo_class"
    t.integer  "allergen_celery_class"
    t.integer  "allergen_parsley_class"
    t.integer  "allergen_yamaimo_class"
    t.integer  "allergen_hourensou_class"
    t.integer  "allergen_kabocha_class"
    t.integer  "allergen_hitoinsulin_food_class"
    t.integer  "allergen_gelatin_class"
    t.integer  "allergen_goma_class"
    t.integer  "allergen_mustard_class"
    t.integer  "allergen_kaichu_class"
    t.integer  "allergen_anisakis_class"
    t.integer  "allergen_hitoinsulin_etc_class"
    t.integer  "allergen_mitsubachi_class"
    t.integer  "allergen_suzumebachi_class"
    t.integer  "allergen_ashinagabachi_class"
    t.integer  "allergen_gokiburi_class"
    t.integer  "allergen_yusurika_class"
    t.integer  "allergen_ga_class"
    t.integer  "allergen_yabuka_class"
    t.integer  "allergen_doubutsuJyouhi_class"
    t.integer  "allergen_syokumotsu_class"
    t.integer  "allergen_kokumotsu_class"
    t.integer  "allergen_ineka_class"
    t.integer  "allergen_kabi_class"
    t.integer  "allergen_zassou_class"
    t.datetime "created_at",                                                  null: false
    t.datetime "updated_at",                                                  null: false
    t.index ["user_id"], name: "index_iges_on_user_id"
  end

  create_table "microposts", force: :cascade do |t|
    t.text     "content"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string   "picture"
    t.index ["user_id", "created_at"], name: "index_microposts_on_user_id_and_created_at"
    t.index ["user_id"], name: "index_microposts_on_user_id"
  end

  create_table "relationships", force: :cascade do |t|
    t.integer  "follower_id"
    t.integer  "followed_id"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.index ["followed_id"], name: "index_relationships_on_followed_id"
    t.index ["follower_id", "followed_id"], name: "index_relationships_on_follower_id_and_followed_id", unique: true
    t.index ["follower_id"], name: "index_relationships_on_follower_id"
  end

  create_table "users", force: :cascade do |t|
    t.string   "name"
    t.string   "email"
    t.datetime "created_at",                                null: false
    t.datetime "updated_at",                                null: false
    t.string   "password_digest"
    t.boolean  "admin",                     default: false
    t.text     "self_introduction"
    t.integer  "rank"
    t.integer  "title_of_honor"
    t.integer  "latest_ige_id"
    t.integer  "latest_ige_value"
    t.boolean  "allergen_sort_inekakafun",  default: false
    t.boolean  "allergen_sort_zassoukafun", default: false
    t.boolean  "allergen_sort_jyukikafun",  default: false
    t.boolean  "allergen_sort_chiri",       default: false
    t.boolean  "allergen_sort_dani",        default: false
    t.boolean  "allergen_sort_shinkin",     default: false
    t.boolean  "allergen_sort_saikin",      default: false
    t.boolean  "allergen_sort_doubutsu",    default: false
    t.boolean  "allergen_sort_syokugyou",   default: false
    t.boolean  "allergen_sort_tamago",      default: false
    t.boolean  "allergen_sort_nyuuseihin",  default: false
    t.boolean  "allergen_sort_gyorui",      default: false
    t.boolean  "allergen_sort_koukakurui",  default: false
    t.boolean  "allergen_sort_ikatako",     default: false
    t.boolean  "allergen_sort_komugi",      default: false
    t.boolean  "allergen_sort_komugiigai",  default: false
    t.boolean  "allergen_sort_nikurui",     default: false
    t.boolean  "allergen_sort_mamerui",     default: false
    t.boolean  "allergen_sort_kudamonorui", default: false
    t.boolean  "allergen_sort_sonota",      default: false
    t.boolean  "allergen_sort_kiseityuu",   default: false
    t.boolean  "allergen_sort_yakubutsu",   default: false
    t.boolean  "allergen_sort_kontyuu",     default: false
    t.boolean  "allergen_sort_maruti",      default: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end

end
